[tox]
minversion = 1.8
basepython = python3.12
envlist = py312-ansible{9,10}
skipsdist = true

[testenv]
passenv = *
deps =
    -r tox-requirements.txt
    ansible9: ansible>=9.0,<10.0
    ansible10: ansible>=10.0,<11.0
commands =
    {posargs:molecule test -s compatibility --destroy always}
