---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/ubuntu:22.04
    pre_build_image: yes
    command: /bin/bash -c "while true; do sleep 1; done"
    privileged: false
provisioner:
  name: ansible
verifier:
  name: ansible
